DROP SEQUENCE MVCBOARDSEQ;
DROP TABLE MVCBOARD;

CREATE SEQUENCE MVCBOARDSEQ;

--번호, 작성자, 제목, 내용, 작성일
CREATE TABLE MVCBOARD(
	SEQ NUMBER PRIMARY KEY,
	WRITER VARCHAR2(1000) NOT NULL,
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REGDATE DATE NOT NULL
);

INSERT INTO MVCBOARD VALUES(MVCBOARDSEQ.NEXTVAL,'관리자','TEST제목','TEST내용',SYSDATE);

SELECT SEQ,WRITER,TITLE,CONTENT,REGDATE FROM MVCBOARD ORDER BY SEQ DESC;